parameters:

services:

    core.blog:
        class: AppBundle\Services\Blog
        arguments: ["@doctrine.orm.entity_manager", "@form.factory", "@session", "@security.token_storage", "@serializer"]
